export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const ADD_TODO = "ADD_TODO";

export const TOGGLE_TODO = "TOGGLE_TODO";

export const COMPLETE_ALL_TODO = "COMPLETE_ALL_TODO";

export const GET_TODO = "GET_TODO";

export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";

export const GET_TODO_FAILED = "GET_TODO_FAILED";

export const LOGIN_REQUESTING = "LOGIN_REQUESTING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILED = "LOGIN_ERROR";

export const LOG_OUT = "LOG_OUT";

export const TOKEN_REFRESH_REQUESTING = "TOKEN_REFRESH_REQUESTING";

export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS";

export const TOKEN_REFRESH_FAILED = "TOKEN_REFRESH_FAILED";
